# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-TempDatabase
version:      0.12
version_from: lib/Test/TempDatabase.pm
installdirs:  site
requires:
    DBD::Pg:                       0
    DBI:                           0
    File::Slurp:                   
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
